require "mkmf"

have_library("fluidsynth", "fluid_audio_driver_t")
have_library("freetype", "FT_Init_FreeType")
have_library("png", "png_create_read_struct")
have_library("ogg", "oggpack_writeinit")
have_library("OpenAL32", "alDopplerFactor")
have_library("ssl", "SSL_new")
have_library("physfs", "PHYSFS_init")
have_library("pixman", "pixman_region32_init")
have_library("SDL2", "SDL_Init")
have_library("SDL2_image", "IMG_Init")
have_library("SDL2_sound", "Sound_GetLinkedVersion")
have_library("theora", "theora_version_string")
have_library("uchardet", "uchardet_new")
have_library("vorbis", "vorbis_info_init")